spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-server
          uri: ${AUTH_SERVER_URI}  # ?? ??? ??? ??? ??
          predicates:
            - Path=/auth/**
        - id: order-service
          uri: ${ORDER_SERVER_URI}  # ?? ??? ??? ??? ??
          predicates:
            - Path=/orders/**
            - Path=/products/**
            - Path=/users/**
            - Path=/payments/**
            - Path=/cart/**
            - Path=/admin/**
            - Path=/stores/**
            - Path=/storeCategories/**
            - Path=/productCategories/**

server:
  port: 19091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/